services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: dev
    image: skribbl-server-dev
    container_name: skribbl-server-dev
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      target: dev
    image: skribbl-client-dev
    container_name: skribbl-client-dev

  redis:
    image: redis:7-alpine
    container_name: skribbl-redis
    ports:
      - '6379:6379'
